bundler_args: --without development
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - jruby-head
  - rbx-2
  - ruby-head
gemfile:
  - Gemfile
  - Gemfile-0.7.rb
  - Gemfile-0.8.rb
env:
  - LC_ALL=C LANG=C
  - LC_ALL=en_US.UTF-8 LANG=C
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: 2.2.2
  fast_finish: true
